# config/packages/fos_rest.yaml

fos_rest:
    body_listener: true

    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }

    zone:
        - { path: ^/api/v1/* }
